version: 2
jobs:
  test:
    github-token: b60a17ea5b1e7c794c0bb5c2c745cb78cd98495f
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: sudo npm install -g gitbook-cli
#      - run: sudo npm install -g gitbook
      - run: sudo npm install -g gh-pages
      - run: gitbook install
      - run: gitbook build
      - run: git config --global user.email "xu_yanfeng@126.com"
      - run: git config --global user.name "774177933@qq.com"
      - run: git config --global user.password "b60a17ea5b1e7c794c0bb5c2c745cb78cd98495f"
      - run: gh-pages -d _book

workflows:
  version: 2
  test:
    jobs:
      - test
