version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: sudo npm install -g gitbook-cli
#      - run: sudo npm install -g gitbook
      - run: sudo npm install -g gh-pages
      - run: gitbook install
      - run: gitbook build
      - run: git config --global user.email $GH_EMAIL
      #      - run: git config --global user.name "xu_yanfeng*circle-ci"
      - run: git config --global user.name $GH_NAME
      - run: gh-pages -d _book -m "circleci-auto"


workflows:
  version: 2
  test:
    jobs:
      - test
