version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: npm install -g gitbook
      - run: npm install -g gitbook-cli
      - run: npm install -g gh-pages
      - run: gitbook install
      - run: gitbook build
      - run: gh-pages -d _book

workflows:
  version: 2
  test:
    jobs:
      - test
